/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#32353c",
        "inverse-primary": "#005ac2",
        "surface-container": "#1d2027",
        "secondary-container": "#571bc1",
        "secondary-fixed-dim": "#d0bcff",
        "surface-dim": "#10131a",
        "secondary": "#d0bcff",
        "background": "#10131a",
        "primary-fixed": "#d8e2ff",
        "on-surface": "#e1e2ec",
        "surface-container-highest": "#32353c",
        "surface-bright": "#363941",
        "on-error-container": "#ffdad6",
        "tertiary": "#ffb95f",
        "on-tertiary": "#472a00",
        "on-surface-variant": "#c2c6d6",
        "outline": "#8c909f",
        "on-secondary-container": "#c4abff",
        "outline-variant": "#424754",
        "surface-container-lowest": "#0b0e15",
        "error-container": "#93000a",
        "surface": "#10131a",
        "surface-container-low": "#191b23",
        "on-primary": "#002e6a",
        "surface-tint": "#adc6ff",
        "tertiary-container": "#ca8100",
        "error": "#ffb4ab",
        "on-secondary": "#3c0091",
        "primary-container": "#4d8eff",
        "primary": "#adc6ff",
        "on-error": "#690005",
        "on-primary-container": "#00285d",
        "surface-container-high": "#272a31",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        hanken: ["Hanken Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
